#!/usr/bin/env python3
# Fern-RTLSDR, an RTL-SDR input module for FernSDR.
# SPDX-License-Identifier: GPL-2.0-or-later
"""Writes a C++ source file that carries the licence texts and author lists of
the libraries linked into the module, for fern-rtlsdr --notices. A package
holds only the executable, so these must travel inside it.

    embed_notices.py FILE... > notices.cpp
"""
import sys


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: embed_notices.py FILE...")
    parts = []
    for path in sys.argv[1:]:
        text = open(path, encoding="utf-8").read().rstrip()
        parts.append("==== %s ====\n\n%s\n" % (path, text))
    notices = "\n\n".join(parts)
    out = ["// Generated by tools/embed_notices.py; do not edit.", "", "namespace fern {", "",
           "extern const char embedded_notices[];", "const char embedded_notices[] ="]
    # Adjacent short literals rather than one raw string, whose length some
    # compilers limit.
    escaped = notices.replace("\\", "\\\\").replace('"', '\\"')
    lines = escaped.split("\n")
    for line in lines[:-1]:
        out.append('    "%s\\n"' % line)
    out.append('    "%s";' % lines[-1])
    out += ["", "}  // namespace fern", ""]
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
